export const AuthActionTypes = {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
};
export const SearchActionTypes = {
  SEARCH_BY_PLAYLIST_START: 'SEARCH_BY_PLAYLIST_START',
  SEARCH_BY_PLAYLIST_SUCCESS: 'SEARCH_BY_PLAYLIST_SUCCESS',
  SEARCH_BY_PLAYLIST_FAIL: 'SEARCH_BY_PLAYLIST_FAIL',
};
