export const AuthActionTypes = {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
};
export const SearchActionTypes = {
  SEARCH_SONGS_START: 'SEARCH_SONGS_START',
  SEARCH_SONGS_SUCCESS: 'SEARCH_SONGS_SUCCESS',
  SEARCH_SONGS_FAIL: 'SEARCH_SONGS_FAIL',
};
