export const AuthActionTypes = {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
};
export const SearchActionTypes = {
  SEARCH_SONGS_START: 'SEARCH_SONGS_START',
  SEARCH_SONGS_SUCCESS: 'SEARCH_SONGS_SUCCESS',
  SEARCH_SONGS_FAIL: 'SEARCH_SONGS_FAIL',

  GET_DISCOVER_SONGS_START: 'GET_DISCOVER_SONGS_START',
  GET_DISCOVER_SONGS_SUCCESS: 'GET_DISCOVER_SONGS_SUCCESS',
  GET_DISCOVER_SONGS_FAIL: 'GET_DISCOVER_SONGS_FAIL',
};

export const SongsActionTypes = {
  GET_SONGS_START: 'GET_SONGS_START',
  GET_SONGS_SUCCESS: 'GET_SONGS_SUCCESS',
  GET_SONGS_FAIL: 'GET_SONGS_FAIL',

  GET_RECENT_SONGS_START: 'GET_RECENT_SONGS_START',
  GET_RECENT_SONGS_SUCCESS: 'GET_RECENT_SONGS_SUCCESS',
  GET_RECENT_SONGS_FAIL: 'GET_RECENT_SONGS_FAIL',

  GET_PLAYLIST_START: 'GET_PLAYLIST_START',
  GET_PLAYLIST_SUCCESS: 'GET_PLAYLIST_SUCCESS',
  GET_PLAYLIST_FAIL: 'GET_PLAYLIST_FAIL',

  UPDATE_RECENTS_START: 'UPDATE_RECENTS_START',
  UPDATE_RECENTS_SUCCESS: 'UPDATE_RECENTS_SUCCESS',
  UPDATE_RECENTS_FAIL: 'UPDATE_RECENTS_FAIL',
};
